# Generated by Django 5.1.5 on 2025-10-13 19:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_images/default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
