# Generated by Django 5.1.5 on 2025-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assign_to',
            field=models.ManyToManyField(default=1, related_name='events', to='events.participant'),
        ),
    ]
