# Generated by Django 5.1.5 on 2025-10-13 19:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=cloudinary.models.CloudinaryField(blank=True, default='events_asset/default-image.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
