# Generated by Django 5.1.5 on 2025-02-17 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_participant_alter_event_assign_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(blank=True, related_name='rsvp_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
